const $=s=>document.querySelector(s);const key="jinsui_";let page="home",sel=new Date(),cal=new Date();
const get=(k,d)=>{try{let x=localStorage.getItem(key+k);return x===null?d:JSON.parse(x)}catch{return d}};const set=(k,v)=>localStorage.setItem(key+k,JSON.stringify(v));
const pad=n=>String(n).padStart(2,"0"), dk=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`, money=n=>"¥"+Number(n||0).toFixed(2);
function enter(){let p=$("#pw").value,c=$("#pw2").value,s=get("password",null);if(!s){if(!/^\d{4,12}$/.test(p))return $("#err").textContent="请输入4～12位数字密码";if(p!==c)return $("#err").textContent="两次密码不一致";set("password",p)}else if(p!==s)return $("#err").textContent="密码不正确";$("#lock").hidden=true;$("#app").hidden=false;render()}
function logout(){$("#app").hidden=true;$("#lock").hidden=false;$("#pw").value="";$("#pw2").value=""}
if(get("password",null)){$("#hint").textContent="请输入密码进入锦岁";$("#pw2").hidden=true}
function go(p){page=p;document.querySelectorAll("nav button").forEach((b,i)=>b.classList.toggle("active",["home","account","calendar","diary","settings"][i]===p));render()}
function render(){let d=new Date();$("#date").textContent=`${d.getFullYear()}年${d.getMonth()+1}月${d.getDate()}日`;({home,account,calendar,diary,settings}[page])()}
function accounts(){return get("accounts",[])}function diaries(){return get("diaries",[])}
function home(){let a=accounts(),m=a.filter(x=>x.date.slice(0,7)===dk(new Date()).slice(0,7)),inc=m.filter(x=>x.type==="in").reduce((s,x)=>s+x.amount,0),out=m.filter(x=>x.type==="out").reduce((s,x)=>s+x.amount,0);$("#main").innerHTML=`<div class=title>今天，也要好好生活</div><div class=desc>记录生活，也记录一点点变好的自己。</div><div class=hero><b>${["平安顺遂","心想事成","万事如意"][new Date().getDate()%3]}</b><p class=sub>${dk(new Date())}</p><div class=actions><button class=pill onclick=addAccount()>＋记一笔</button><button class=pill onclick="go('diary')">✎ 写日记</button></div></div><div class=grid><div class=card><h3>本月支出</h3><div class="num red">${money(out)}</div></div><div class=card><h3>本月收入</h3><div class="num green">${money(inc)}</div></div></div><div class=card><h3>最近账目</h3>${a.slice(0,5).map(row).join("")||'<div class=empty>还没有账目</div>'}</div>`}
function row(x){return `<div class=row><div>🧾 ${esc(x.title)}<div class=sub>${x.date} · ${esc(x.cat)}</div></div><b class=${x.type==="in"?"green":"red"}>${x.type==="in"?"+":"-"}${money(x.amount)}</b></div>`}
function account(){let a=accounts();$("#main").innerHTML=`<div class=title>记账</div><div class=desc>每一笔都值得被看见。</div><div class=card><button class="primary" onclick=addAccount()>＋ 新增账目</button></div><div class=card><h3>全部账目</h3>${a.map(row).join("")||'<div class=empty>暂无账目</div>'}</div>`}
function addAccount(){modal("记一笔",`<div class=field><label>类型</label><select id=mt><option value=out>支出</option><option value=in>收入</option></select></div><div class=field><label>金额</label><input id=ma type=number step=.01 placeholder=0></div><div class=field><label>项目</label><input id=mn placeholder=例如：早餐></div><div class=field><label>分类</label><select id=mc><option>餐饮</option><option>购物</option><option>交通</option><option>居住</option><option>娱乐</option><option>工资</option><option>其他</option></select></div><div class=actions><button class=pill onclick=closeModal()>取消</button><button class=primary onclick=saveAccount()>保存</button></div>`)}
function saveAccount(){let n=$("#mn").value.trim(),a=+$("#ma").value;if(!n||!a)return alert("请填写完整");let x=accounts();x.unshift({id:Date.now(),date:dk(new Date()),title:n,amount:a,type:$("#mt").value,cat:$("#mc").value});set("accounts",x);closeModal();render()}
function calendar(){let y=cal.getFullYear(),m=cal.getMonth()+1,first=new Date(y,m-1,1).getDay(),days=new Date(y,m,0).getDate(),td=dk(new Date());let h=`<div class=title>日历</div><div class=desc>看看时间，也看看留下的记录。</div><div class=card><div class=row><button class=pill onclick=chg(-1)>‹</button><b>${y}年${m}月</b><button class=pill onclick=chg(1)>›</button></div><div class=week><span>日</span><span>一</span><span>二</span><span>三</span><span>四</span><span>五</span><span>六</span></div><div class=calendar>`;for(let i=0;i<first;i++)h+="<span></span>";for(let n=1;n<=days;n++){let k=`${y}-${pad(m)}-${pad(n)}`,has=accounts().some(x=>x.date===k)||diaries().some(x=>x.date===k);h+=`<button class="${k===td?"today ":""}${has?"has":""}" onclick="pick('${k}')">${n}</button>`}h+="</div></div>";$("#main").innerHTML=h}
function chg(n){cal.setMonth(cal.getMonth()+n);calendar()}function pick(k){let p=k.split("-").map(Number);sel=new Date(p[0],p[1]-1,p[2]);go("diary")}
function diary(){let k=dk(sel),d=diaries().find(x=>x.date===k);$("#main").innerHTML=`<div class=title>日记</div><div class=desc>${k} · 给今天留下一句话。</div><div class=card><div class=field><label>心情</label><select id=dm><option>平静</option><option>开心</option><option>充实</option><option>疲惫</option><option>难过</option></select></div><div class=field><textarea id=dt placeholder="今天发生了什么？">${esc(d?.text||"")}</textarea></div><div class=actions><button class=pill onclick=saveDiary()>保存</button>${d?'<button class=pill onclick=delDiary()>删除</button>':""}</div></div>`}
function saveDiary(){let a=diaries().filter(x=>x.date!==dk(sel));a.unshift({date:dk(sel),mood:$("#dm").value,text:$("#dt").value});set("diaries",a);alert("日记已保存");render()}function delDiary(){set("diaries",diaries().filter(x=>x.date!==dk(sel)));render()}
function settings(){$("#main").innerHTML=`<div class=title>设置</div><div class=desc>锦岁的数据默认只保存在当前设备。</div><div class=card><div class=row><div><b>修改密码</b><div class=sub>本地密码</div></div><button class=pill onclick=changePwd()>修改</button></div><div class=row><div><b>数据备份</b><div class=sub>导出JSON文件</div></div><button class=pill onclick=backup()>导出</button></div><div class=row><div><b>关于锦岁</b><div class=sub>记账 · 日历 · 日记 · 生活</div></div><span>1.0</span></div></div>`}
function changePwd(){modal("修改密码",`<div class=field><label>新密码</label><input id=np type=password inputmode=numeric maxlength=12></div><button class=primary onclick=savePwd()>保存</button>`)}function savePwd(){let p=$("#np").value;if(!/^\d{4,12}$/.test(p))return alert("请输入4～12位数字密码");set("password",p);closeModal();alert("密码已修改")}
function backup(){let b=new Blob([JSON.stringify({accounts:accounts(),diaries:diaries()},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="锦岁数据备份.json";a.click()}
function modal(t,b){$("#modal").innerHTML=`<div><h2>${t}</h2>${b}</div>`;$("#modal").hidden=false}function closeModal(){$("#modal").hidden=true}$("#modal").onclick=e=>{if(e.target.id==="modal")closeModal()};function esc(s){return String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
if("serviceWorker"in navigator&&location.protocol==="https:")navigator.serviceWorker.register("sw.js");go("home");